name: Discord Message Notify

on:
  push:
    branches: [ IBS ]
  pull_request:
    branches: [ IBS ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Message Notify
      uses: Ilshidur/action-discord@master
      env:
       DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
       args: |
        **${{ github.actor }}** が `${{ github.ref_name }}` で **${{ github.event_name }}** を実行しました。

        **リポジトリ:** ${{ github.repository }}
        **コミットメッセージ:** > ${{ github.event.head_commit.message || github.event.pull_request.title }}

        **詳細:**
        ${{ github.event.compare || github.event.pull_request.html_url }}