name: EditorBuild

on:
  push:
    branches:
      - master
      - IBS
      - AL4
      - CG
      - GE
      - WP0

env:
  # リポジトリのルートディレクトリを基点としたソリューションファイルのパス
  SOLUTION_FILE_PATH: project/Irufemi.sln
  # Visual Studio の構成
  CONFIGURATION: Editor

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2.0.0

      - name: Restore NuGet Packages
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build for IBS Branch (Application_team only)
        if: github.ref_name == 'IBS'
        run: |
          msbuild ${{ env.SOLUTION_FILE_PATH }} /t:Application_team /p:Platform=x64,Configuration=${{ env.CONFIGURATION }},PlatformToolset=v143

      - name: Build for Other Branches (Whole Solution)
        if: github.ref_name != 'IBS'
        run: |
          msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Platform=x64,Configuration=${{ env.CONFIGURATION }},PlatformToolset=v143
